baseURL = "https://docs.hofstadter.io/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Hofstadter Documentation"
# theme = ""


enableGitInfo = true

pygmentsCodeFences = true
pygmentsStyle = "solarized-dark"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[params]
ordersectionsby = "weight" # ordersectionsby = "title"
disableSearch = false # default is false
disableReadmoreNav = false # set true to hide prev/next navigation, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
googleAnalytics = "GTM-5HFC5MV"
github_project_repo = "https://github.com/hofstadter-io/hof"
github_repo = "https://github.com/hofstadter-io/hof-docs"
time_format_default = "January 2, 2006"
cuedocBase = "https://pkg.go.dev/cuelang.org/go@v0.3.0-alpha6"
onetrust = "008b73d8-bcd7-4901-accd-6d2e78b3e0a9"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
# name = "<i class='fab fa-github'></i> github"
name = "github"
url = "https://github.com/hofstadter-io"
weight = 1

[[menu.shortcuts]]
# name = "<i class='far fa-'></i> chat"
name = "chat"
url = "https://join.slack.com/t/hofstadter-io/shared_invite/zt-e5f90lmq-u695eJur0zE~AG~njNlT1A"
weight = 2

[[menu.shortcuts]]
name = "home"
url = "https://hofstadter.io"
weight = 3

