apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hof-docs
  namespace: websites
  labels:
    app: hof-docs
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod

    kubernetes.io/configuration-snippet: |
      location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        expires 1h;
        access_log off;
        add_header Cache-Control "public";
      }
      location / {
        expires -1;
      }

spec:
  tls:
  - hosts:
    - docs.hofstadter.io
    secretName: docs-hofstadter-io-tls

  rules:
  - host: docs.hofstadter.io
    http:
      paths:
        - backend:
            serviceName: hof-docs
            servicePort: 80

